name: "Dependant Jobs"
on:
  push:

env:
  FOO: "foo"
  BAR: "bar"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      FOO: ${FOO}
      BAR: ${BAR}
    steps:
      - run: echo "This is the initial setup job"

  intermediate_job:
    runs-on: ubuntu-latest
    needs:
      - setup
    outputs:
      BUZZ: buzz
    steps:
      - run: |
          echo "This is an intermediate job that depends on setup"
          echo "setup.FOO: ${{ needs.setup.outputs.FOO }}"
          echo "setup.BAR: ${{ needs.setup.outputs.BAR }}"

  dependant_job:
    runs-on: ubuntu-latest
    needs:
      - setup
      - intermediate_job
    steps:
      - run: |
          echo "This job depends on the intermediate_job, but its execution depends on an output from the setup job"
          echo "setup.FOO: ${{ needs.setup.outputs.FOO }}"
          echo "setup.BAR: ${{ needs.setup.outputs.BAR }}"
