name: "Manually triggered workflow"
on:
  workflow_dispatch:
    inputs:
      message:
        required: false
        default: "Hello world!"
        description: "The message to be printed"
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.message }}"