name: "Matrix extension and exclusion"

on:
  push:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var1:
          - foo
          - bar
        var2:
          - 1
        include:
          - var1: foo
            var2: 2
        exclude:
          - var1: foo
            var2: 1
    steps:
      - run: echo "${{matrix.var1}} - ${{matrix.var2}}"
