name: "Reusable workflow"
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        default: "Hello world!"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.message }}
  say_bye:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye folks!"