name: "Reusable workflow with status check"

on:
  push:

jobs:
  call_reusable:
    uses: ./.github/workflows/reusable-workflow.yml

  result:
    needs: call_reusable
    runs-on: ubuntu latest
    if: always()
    steps:
      - name: "Check result"
        if: needs.call_reusable.result != 'success'
        run: exit 1
