name: "Reusable workflow with status check"

on:
  workflow_dispatch:
    inputs:
      run_subworkflow:
        type: choice
        description: Call subworkflow
        options:
          - yes
          - no

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.run_subworkflow }}

  call_reusable:
    if: github.event.inputs.run_subworkflow == 'yes'
    uses: ./.github/workflows/reusable-workflow.yml

  result:
    needs: call_reusable
    runs-on: ubuntu latest
    if: github.event.inputs.run_subworkflow == 'yes'
    steps:
      - name: "Check result"
        if: needs.call_reusable.result != 'success'
        run: exit 1
