name: "Tag triggered Workflow"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'test-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
