name: "Testing Outputs"
on:
  push:

env:
  FOO: "hola"
  BAR: "que ase"

jobs:
  outputs_from_env_vars:
    runs-on: ubuntu-latest
    outputs:
      FOO: ${FOO}
      BAR: ${BAR}
    steps:
      - run: ""

  consuming_outputs:
    runs-on: ubuntu-latest
    needs:
      - outputs_from_env_vars
    steps:
      - run: |
          echo "FOO: ${{ needs.outputs_from_env_vars.outputs.FOO }}"
          echo "BAR: ${{ needs.outputs_from_env_vars.outputs.BAR }}"
