name: "Testing Outputs"
on:
  push:

env:
  FOO: foo
  BAR: bar

jobs:
  outputs_from_env_vars:
    runs-on: ubuntu-latest
    outputs:
      FOO: ${FOO}
      BAR: ${BAR}
    steps:
      - run: echo "done"

  consuming_outputs:
    runs-on: ubuntu-latest
    requires:
      - outputs_from_env_vars
    steps:
      - run: |
          echo "FOO: ${{ needs.outputs_from_env_vars.outputs.FOO }}"
          echo "BAR: ${{ needs.outputs_from_env_vars.outputs.BAR }}"
