name: "Matrix status check"
on:
  push: 

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo: [1, 2, 3]
    steps:
      - name: Fail if even
        if: ${{ matrix.foo }} % 2 == 0
        run: exit 1

  status-check:
    needs: matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: needs.matix.status != 'success'
        run: exit 1
