name: "Conditionality"

on:
  workflow_call:
    inputs:
      run-hello:
        description: 'Run the hello world job'
        default: 'true'
        type: string

jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: ${{ inputs.run-hello == 'true' }}
    steps:
      - run: |
          echo "hello world"

  final:
    needs: hello-world
    runs-on: ubuntu-latest
    if: ${{ inputs.run-hello == 'true' || needs.hello-world.result == 'skipped' }}
    steps:
      - run: |
          echo "Final job run"
