name: "Dynamic env vars"
on:
  push: 

env:
  FOO: foo

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BAR=bar" >> $GITHUB_ENV
        name: Adds a new env var
      - run: env

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: env
