name: "Playground workflow"
on:
  push: 

env:
  DOCKER_USERNAME: beni0888

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: beni0888/poc
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: list image tags
        run: |
          echo ${{steps.meta.outputs.json}}
#          for tag in ${{ fromJSON(steps.meta.outputs.json.tags) }}; do
#            echo "- $tag"
#          done;
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and load docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
#          outputs: type=docker,dest=/tmp/beni0888-poc.tar
          load: true
      - name: list loaded images
        run: docker images
      - name: run image
        run: docker run --rm beni0888/poc
      - name: push image
        run: docker push beni0888/poc