name: "Custom Action"
on:
  push: 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ./.github/custom-action.yml
        with:
          who-to-greet: jesus
