name: "Playground workflow"
on:
  push: 

env:
  DOCKER_USERNAME: beni0888
  IMG_TAG: foo

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - run: whoami

  docker_build_and_push:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: beni0888/poc
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: list image tags
        run: |
          while read tag; do
            echo "- $tag"
          done <<EOF
          ${{steps.meta.outputs.tags}}
          EOF
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and load docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/beni0888-poc.tar
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: beni0888_poc
          path: /tmp/beni0888-poc.tar
      - name: Load image
        run: |
          docker load --input /tmp/beni0888-poc.tar
          docker image ls -a
      - name: push image
        run: |
          while read tag; do
            docker push $tag
          done <<EOF
          ${{steps.meta.outputs.tags}}
          EOF


  docker_build_and_push_2:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: beni0888/poc
          flavor: |
            latest=true
          tags: |
            type=sha
            type=raw,value=${IMG_TAG}
      - name: list image tags
        run: |
          while read tag; do
            echo "- $tag"
          done <<EOF
          ${{steps.meta.outputs.tags}}
          EOF
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/beni0888-poc.tar
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: beni0888_poc
          path: /tmp/beni0888-poc.tar
      - name: Push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

  dependant_job:
    runs-on: ubuntu-latest
    needs:
      - docker_build_and_push_2
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          path: /tmp/images
      - run: echo ${{ steps.download.outputs.download-path }}