name: "Multiple jobs status check"

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  status-check:
    if: always()
    needs:
      - job1
      - job2
    runs-on: ubuntu-latest
    steps:
      - name: "Check all jobs result"
        if: needs.job1.result != 'success' || needs.job2.result != 'success'
        run: exit 1
